### ISSUE TITLE
Méthode de déploiement de mviewer

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#34]
Je me dis qu'il serait utile de décrire dans l'aide de l'outil la méthode à suivre pas à pas pour déployer une nouvelle instance de mviewer. J'ai l'impression qu'il y a pas mal de choses à configurer / adapter lorsqu'on veut se lancer (contrairement à ce que laisse penser le chapitre "déploiement" du readme) :
- création d'un thème (fichier css, logos, favicon, panel-footer.png...)
- modification du contenu du fichier index.html
- modification du contenu du fichier contact.html
- ajout des aperçus pour les couches de fond

Qu'en pensez-vous ?
Je suis évidemment prêt à contribuer à l'amélioration de la doc.

De plus, je trouve assez délicat de devoir modifier des fichiers du mviewer localisés à tous les niveaux de l'arborescence. Je trouve que cela complique les choses quand on veut simplement mettre à jour le mviewer sans écraser les paramètres que l'on a défini pour un déploiement particulier.
Est-ce que je me trompe ? Est-ce qu'il y a une manière simple de bien séparer le coeur de l'appli et les personnalisations ?

**Comment by spelhate** [comment]
Pour ma part, je ne modifie pas index.htmlLes personnalisations portent uniquement sur les fichiers de paramétrages (config.xml et des styles personnalisés que je dépose dans css/themes (exemple geobretagne.css). Ensuite je fais référence au style que je souhaite utiliser dans le config.xml, dans le nœud application avec le paramètre style="" ex : style="css/themes/geobretagne.css"Pour info, le style a été généré avec le générateur de style suivant : https://themeroller.jquerymobile.com/ Démo ici : http://kartenn.region-bretagne.fr/mviewer/?config=demo/geobretagne.xml Sinon pour aider les utilisateurs il y a cette ressource à améliorer mais qui a le mérite d'exister : http://kartenn.region-bretagne.fr/mviewer/demo/  Sébastien PelhateChef de projet informatique et SIGPôle Observatoire et Information géographique (POLOI)Service connaissance, observation, planification et prospective (SCOPP) Direction de l'aménagement et de l'égalité - Région BretagneTél. : 02 99 27 96 47-----"Benjamin C." <notifications@github.com> a écrit : ----- 
A : geobretagne/mviewer <mviewer@noreply.github.com>De : "Benjamin C." <notifications@github.com>Date : 15/11/2016 16:25Objet : [geobretagne/mviewer] Méthode de déploiement de mviewer (#34)Je me dis qu'il serait utile de décrire dans l'aide de l'outil la méthode à suivre pas à pas pour déployer une nouvelle instance de mviewer. J'ai l'impression qu'il y a pas mal de choses à configurer / adapter lorsqu'on veut se lancer (contrairement à ce que laisse penser le chapitre "déploiement" du readme) :création d'un thème (fichier css, logos, favicon, panel-footer.png...)modification du contenu du fichier index.htmlmodification du contenu du fichier contact.htmlajout des aperçus pour les couches de fondQu'en pensez-vous ?Je suis évidemment prêt à contribuer à l'amélioration de la doc.De plus, je trouve assez délicat de devoir modifier des fichiers du mviewer localisés à tous les niveaux de l'arborescence. Je trouve que cela complique les choses quand on veut simplement mettre à jour le mviewer sans écraser les paramètres que l'on a défini pour un déploiement particulier.Est-ce que je me trompe ? Est-ce qu'il y a une manière simple de bien séparer le coeur de l'appli et les personnalisations ?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by bchartier** [comment]
J'aimerais bien ne pas modifier le fichier index.html mais ce fichier contient des informations typiquement bretonnes qui ne sont pas forcément pertinentes dans le cas d'un déploiement dans une autre collectivité : cf. les lignes suivantes https://github.com/geobretagne/mviewer/blob/master/index.html#L102-L137

**Comment by bchartier** [comment]
> Sinon pour aider les utilisateurs il y a cette ressource à améliorer mais qui a le mérite d'exister : http://kartenn.region-bretagne.fr/mviewer/demo/

Cette ressource est effectivement très intéressante. J'avais bien vu le fichier en question mais je ne l'avais pas lancé dans un navigateur. Il faut que je la réutilise !

**Comment by spelhate** [comment]
Ok. je me charge de dérégionnaliser le mviewer pour éviter de modifier ce fichier. Sébastien PelhateChef de projet informatique et SIGPôle Observatoire et Information géographique (POLOI)Service connaissance, observation, planification et prospective (SCOPP) Direction de l'aménagement et de l'égalité - Région BretagneTél. : 02 99 27 96 47-----"Benjamin C." <notifications@github.com> a écrit : ----- 
A : geobretagne/mviewer <mviewer@noreply.github.com>De : "Benjamin C." <notifications@github.com>Date : 22/11/2016 14:45Cc: spelhate <sebastien.pelhate@bretagne.bzh>, Comment <comment@noreply.github.com>Objet : Re: [geobretagne/mviewer] Méthode de déploiement de mviewer (#34)J'aimerais bien ne pas modifier le fichier index.html mais ce fichier contient des informations typiquement bretonnes qui ne sont pas forcément pertinentes dans le cas d'un déploiement dans une autre collectivité : cf. les lignes suivantes https://github.com/geobretagne/mviewer/blob/master/index.html#L102-L137—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by bchartier** [comment]
Merci !

**Comment by spelhate** [comment]
Mviewer est désormais dépersonnalisé et complètement relooké.
Exemple : http://kartenn.region-bretagne.fr/kartoviz/

**Comment by bchartier** [comment]
Superbe !

**Comment by hsquividant** [comment]
Magnifique ! Ça mériterait davantage de (geo)com' !

**Comment by spelhate** [comment]
Un immense merci à @Agath21et à tous les contributeurs invisibles pour le travail réalisé.

**Comment by bchartier** [comment]
> Un immense merci à @Agath21 et à tous les contributeurs invisibles pour le travail réalisé.

Vive eux !

**Comment by gpetit** [comment]
Merci !

**Comment by ebocher** [comment]
Merci @spelhate , @Agath21 
Mon collègue @gpetit va travailler sur une proposition de documentation avec readthedoc que nous soumettrons ici https://github.com/geobretagne/mviewer.doc voir #40

**Comment by spelhate** [comment]
Super !
